[server]
headless = true
address = "0.0.0.0"
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#111111"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F4F4F8"
textColor = "#1a1a2e"
font = "sans serif"
